## Append samples of your project ##
resources:
- rbac_v1alpha1_gridosgroup.yaml
- rbac_v1alpha1_gridosrole.yaml
- rbac_v1alpha1_gridosgrouprolebinding.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
